modLoader = "javafml"
loaderVersion = "[0,)"
issueTrackerURL = "${issueTrackerUrl}"
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = '''${description}'''
displayURL = "${websiteUrl}"
updateJSONURL = "${neoForgeUpdateUrl}"
itemIcon = "minecraft:oak_sapling"

[[dependencies.${id}]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoForgeVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion}]"
ordering = "NONE"
side = "BOTH"
